# Generated by Django 5.2.8 on 2026-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plumber", "Plumbing"),
                    ("electrician", "Electrical Repairing"),
                    ("cleaner", "Cleaning"),
                    ("painter", "Painting"),
                    ("gardener", "Gardening"),
                    ("carpenter", "Carpentry"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
