# Generated by Django 5.2.8 on 2026-05-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admin Management",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
    ]
