# Generated by Django 5.2.8 on 2026-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AddField(
            model_name="notification",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="legacy", max_length=100),
            preserve_default=False,
        ),
    ]
