services:
  - type: web
    name: sewasaathi-backend
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /admin/
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    preDeployCommand: python manage.py migrate --noinput
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: EMAIL_BACKEND
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: KHALTI_PUBLIC_KEY
        sync: false
      - key: KHALTI_SECRET_KEY
        sync: false
