# Generated by Django 5.2.8 on 2026-05-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="platformrevenue",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
