# Generated by Django 5.2.8 on 2025-12-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePackage',
        ),
    ]
