# Generated by Django 5.2.8 on 2025-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_servicepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('unit', 'Per Unit'), ('starting', 'Starting From')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('unit', 'Per Unit'), ('starting', 'Starting From')], default='fixed', max_length=20),
        ),
    ]
