# Generated by Django 5.2.8 on 2026-04-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_service_translations_and_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="description",
            new_name="description_key",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="name",
            new_name="name_key",
        ),
        migrations.RenameField(
            model_name="servicecategory",
            old_name="description",
            new_name="description_key",
        ),
        migrations.RenameField(
            model_name="servicecategory",
            old_name="name",
            new_name="name_key",
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("category", "name_key")},
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="description_translations",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="name_translations",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description_translations",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name_translations",
        ),
    ]
