# Generated by Django 5.2.8 on 2026-05-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_rename_description_service_description_key_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="providerservice",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="providerservice",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="providerservice",
            name="service",
        ),
        migrations.DeleteModel(
            name="ProviderAvailability",
        ),
        migrations.DeleteModel(
            name="ProviderService",
        ),
    ]
