# Generated by Django 5.2.8 on 2026-03-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceclaim",
            name="evidence",
            field=models.FileField(upload_to="claim_evidence/"),
        ),
    ]
