# Generated by Django 5.2.8 on 2026-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
