# Generated by Django 5.2.8 on 2026-03-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
