# Generated by Django 5.2.8 on 2026-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_rework",
            field=models.BooleanField(default=False),
        ),
    ]
