# Generated by Django 5.2.8 on 2026-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_booking_is_rework"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
