# Generated by Django 5.2.8 on 2026-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_booking_status_not_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Customer"), ("provider", "Provider")],
                max_length=10,
                null=True,
            ),
        ),
    ]
