# Generated by Django 5.2.8 on 2026-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_booking_commission_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("online", "Online"),
                    ("khalti_v2", "Khalti"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
